### PR TITLE
BUG fixed bug in coadd MOF convergence test; enabled png plotting again

### PR DESCRIPTION
**Pull request by beckermr**
This PR patches a bug in the coadd convergence tests for MOF. 

@NiallMac for viz

### CODE REVIEW

**Comment by beckermr** [comment]
Sorry for all the white space changes. I wrote shit code last time and now it is making life hard.

**Comment by esheldon** [comment]
do I read this correctly (hard to see with the whitespace changes) that the problem is with using a `Namer` that didn't work for coadds?

**Comment by beckermr** [comment]
Yeah. For some reason, when fitting coadds, the final parameter names don't have `coadd_` at the front. So I took that out and special cased the correction to only coadd-only fits.

**Comment by esheldon** [comment]
there is a config parameter to not use the  coadd_ prefix when we only fit coadds. That way people downstream don't have to alter their codes when run on coadds.   Niall has that turned on here

**Comment by esheldon** [comment]
I think we probably need to put this into master as well since we are now running on coadds for the SN fields (they are chip-by-chip so no discontinuities )

**Comment by esheldon** [comment]
This is against master, sorry. I thought the PR was against the version we were testing for the sims.  Unfortunately master has changed too much compared to that version fo this to be useful in those tests.

**Comment by beckermr** [comment]
Yeah the PR against the sim branch didn't work for some reason. We can cherry pick the commit.

**Comment by esheldon** [comment]
OK, I've not done that before, can you take the lead?

**Comment by beckermr** [comment]
Sure. I will make a few PRs and get it merged.

**Comment by beckermr** [comment]
@esheldon which config param controls the renaming for coadds? Right now my if statement is not very specific and I could make the branch more robust by testing on this bit.

**Comment by beckermr** [comment]
LOL. The `use_coadd_prefix` config param doesn't work as expected. The code is still using the non-prefixed parameter internally as far as I can tell. We need to deprecate this pile of trash.

**Comment by beckermr** [comment]
OK. I have cherry picked the commits and tagged a new version here: https://github.com/esheldon/ngmixer/releases/tag/y3v0.9.4b1

**Comment by beckermr** [comment]
This is based on the old `y3v0.9.4b1` branch.

**Pull request merged**
